# Generated by Django 3.1.7 on 2021-03-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommOrder', '0002_wishcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishCart',
        ),
    ]
