# Generated by Django 3.1.7 on 2021-03-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommOrder', '0003_delete_wishcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card_num',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expiry_month',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expiry_year',
        ),
    ]
