# Generated by Django 3.1.7 on 2021-03-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommProduct', '0002_auto_20210301_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_image/'),
        ),
    ]
