# Generated by Django 3.1.7 on 2021-03-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommProduct', '0003_auto_20210301_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category_img/cat_image'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='product_img/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_image/pro_img'),
        ),
    ]
