# Generated by Django 3.1.7 on 2021-03-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommProduct', '0004_auto_20210326_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
