# Generated by Django 3.1.7 on 2021-03-28 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommProduct', '0006_auto_20210328_0357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
