# Generated by Django 3.1.7 on 2021-03-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggrid',
            name='tags',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
