# Generated by Django 3.1.7 on 2021-03-24 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcommProduct', '0003_auto_20210301_1603'),
        ('Blog', '0002_bloggrid_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blogcategry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EcommProduct.category'),
            preserve_default=False,
        ),
    ]
