# Generated by Django 3.1.7 on 2021-03-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_comment_blogcategry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blogcategry',
        ),
    ]
