# Generated by Django 3.1.7 on 2021-03-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_blogcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloggrid',
            name='blogcategory',
        ),
    ]
