# Generated by Django 3.1.7 on 2021-03-25 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcommProduct', '0003_auto_20210301_1603'),
        ('Blog', '0006_remove_bloggrid_blogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggrid',
            name='blogcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EcommProduct.category'),
            preserve_default=False,
        ),
    ]
