# Generated by Django 3.1.7 on 2021-03-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20210326_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggrid',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloggrid',
            name='status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Publish')], max_length=40),
        ),
    ]
