# Generated by Django 3.1.7 on 2021-03-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20210327_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggrid',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Publish', 'Publish')], max_length=40),
        ),
    ]
