# Generated by Django 3.1.7 on 2021-03-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_auto_20210327_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloggrid',
            options={'ordering': ['-created_at']},
        ),
    ]
