# Generated by Django 3.1.7 on 2021-03-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0005_subscriber_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='icon',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
